CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(100) NOT NULL,
  "full_name" varchar(100),
  "bio" text,
  "profile_picture_url" varchar(255),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "friends" (
  "friend_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id1" int NOT NULL,
  "user_id2" int NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "conversations" (
  "conversation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(50),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "participants" (
  "participant_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "conversation_id" int NOT NULL,
  "type" varchar(50)
);

CREATE TABLE "messages" (
  "message_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" int NOT NULL,
  "sender_id" int NOT NULL,
  "content" text NOT NULL,
  "sent_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE INDEX ON "friends" ("user_id1");

CREATE INDEX ON "friends" ("user_id2");

CREATE INDEX ON "friends" ("user_id1", "user_id2");

CREATE INDEX ON "conversations" ("created_at");

CREATE INDEX ON "conversations" ("updated_at");

CREATE INDEX ON "participants" ("user_id");

CREATE INDEX ON "participants" ("conversation_id");

CREATE INDEX ON "messages" ("conversation_id");

CREATE INDEX ON "messages" ("sender_id");

CREATE INDEX ON "messages" ("sent_at");

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id1") REFERENCES "users" ("user_id");

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id2") REFERENCES "users" ("user_id");

ALTER TABLE "participants" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "participants" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("conversation_id");

ALTER TABLE "messages" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("conversation_id");

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("user_id");
